# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-sync-secret
  # namespace: default # Namespace is inherited from kustomization.yaml
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: minio-sync-secret # This is the K8s secret the CronJob will use
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Map K8s secret keys to rclone env vars expected by the CronJob
        # Use uppercase names without hyphens for env vars
        RCLONE_CONFIG_MINIOSRC_TYPE: "s3"
        RCLONE_CONFIG_MINIOSRC_PROVIDER: "Minio"
        RCLONE_CONFIG_MINIOSRC_ENDPOINT: "https://minio-api.tomyail.com"
        RCLONE_CONFIG_MINIOSRC_REGION: "us-east-1"
        RCLONE_CONFIG_MINIOSRC_USE_PATH_STYLE: "true"
        RCLONE_CONFIG_MINIOSRC_FORCE_PATH_STYLE: "true"
        RCLONE_CONFIG_MINIOSRC_V2_AUTH: "true"
        RCLONE_CONFIG_MINIOSRC_ACCESS_KEY_ID: "{{ .MINIO_SRC_ACCESS_KEY_ID }}"
        RCLONE_CONFIG_MINIOSRC_SECRET_ACCESS_KEY: "{{ .MINIO_SRC_SECRET_ACCESS_KEY }}"

        RCLONE_CONFIG_MINIODST_TYPE: "s3"
        RCLONE_CONFIG_MINIODST_PROVIDER: "Minio"
        RCLONE_CONFIG_MINIODST_ENDPOINT: "http://minio.default.svc.cluster.local:9000"
        RCLONE_CONFIG_MINIODST_REGION: "us-east-1"
        RCLONE_CONFIG_MINIODST_USE_PATH_STYLE: "true"
        RCLONE_CONFIG_MINIODST_ACCESS_KEY_ID: "{{ .MINIO_DST_ACCESS_KEY_ID }}"
        RCLONE_CONFIG_MINIODST_SECRET_ACCESS_KEY: "{{ .MINIO_DST_SECRET_ACCESS_KEY }}"
  data:
    # Source MinIO Credentials
    - secretKey: MINIO_SRC_ACCESS_KEY_ID
      remoteRef:
        key: "minio" # Replace with actual BW item ID
        property: "username" # Replace with actual BW field name
    - secretKey: MINIO_SRC_SECRET_ACCESS_KEY
      remoteRef:
        key: "minio" # Replace with actual BW item ID
        property: "password" # Replace with actual BW field name


    - secretKey: MINIO_DST_ACCESS_KEY_ID
      remoteRef:
        key: "minio-dev" # Replace with actual BW item ID
        property: "username" # Replace with actual BW field name
    - secretKey: MINIO_DST_SECRET_ACCESS_KEY
      remoteRef:
        key: "minio-dev" # Replace with actual BW item ID
        property: "password" # Replace with actual BW field name
