
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tailscale-prometheus
spec:
  defaultBackend:
    service:
      name: kube-prometheus-stack-prometheus
      port:
        number: 9090
  ingressClassName: tailscale
  tls:
    - hosts:
        - prometheus