# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
    name: actions-runner-controller-auth
spec:
    secretStoreRef:
        kind: ClusterSecretStore
        name: bitwarden-login
    target:
        name: actions-runner-controller-auth-secret
        template:
            engineVersion: v2
            data:
                ACTION_RUNNER_CONTROLLER_GITHUB_APP_ID: ENC[AES256_GCM,data:9X0cVCxznV+WtR62MPyoWIPkiK7XmCoMLdcXJrPkb2OUsMXcUxP3HBKseaTb,iv:2Zc1cDnFLfTaYtbWyiY3ofCDFocZZ0DRQpUdfflkx58=,tag:XC8aY+zZ74CElMYgRUMNlA==,type:str]
                ACTION_RUNNER_CONTROLLER_GITHUB_INSTALLATION_ID: ENC[AES256_GCM,data:G3Hb+t/nQF2vTP0vMAjzfdoYtVsgL9hmbQLvedhddFF5CyR8paQXNO83ALv02QmOHCIArLXx,iv:Z+u/K8a6cHRgzpJbaRwwVsRN6C1AXAJE40Rj8P5paiQ=,tag:QJpW4bSa588McbqMHElumQ==,type:str]
                ACTION_RUNNER_CONTROLLER_GITHUB_PRIVATE_KEY: ENC[AES256_GCM,data:MgmdhLlmugVMI9h0ZNozvWmfUIm//RRhEwboeoqANLGXQ/CgDMlFbdCGz/7n55tUXpH5BbDctLPQb1rB7mdBmH5CDep88zY7IYRRv0FGnDQB+UuPL74UibmL1R64xOyiY7sLLZRCperRJQD1m8A3I/edVd18d3+kpa4Y015HKmqSREEWZ4Xg8iqRFuUu8wPnHYzjurs7aNf+Jhx4QARoJPByNL1M4ciaPdV5XYmpyNc6J6vlBXWlQPpliWC0NEBikqNGhykXY+LM1tNBZoWs/q/2GfKqET9kgIztl/UB8lyd40Rz+Lb/9zt7WAHIMQcK3uR+ctvX76Awkc5VZdZY7JiK2l4mJ3SreWbCcJWXIPMgEpJM+aFjCmjj/YIV6FaboVKuuUxBtVOzAgOh0ZOYxY46Xk7a9eQCpWLWrc9A7Crhy0J5fxlmPzZCSMlji/G6Kwe0hpMBGyswPQ1dkoeyyUO6UJMDMMKu8hfiga8A6fmM4IG7C3p8TIvV2a8pSMF/GxNEzcu/QG88qzz9DB15+XSCkkQrjlRC5h5JA6o7CDYT3Noj1mUzhJjcokBMvKUw/zhLiB0b3qYOs1gae0r1AR+JNqufQg9Zet2YVj44OB1wgb0JU6bXaKx5nOujuHPfSET4uQZD3hoOOScxfblkoP6ytjcIqvoDkpbx5hpCFc4o4ZpUxSph7GHy7O8zM95LIoKxccVjnpBYnL9QBQe9f+yvUVoaylnKyKF7fW3Yi0CBhcjlNKgPioMSvRWZJeC9xyD8rryrpet7HYpYqEilNlE+AVmbFGcM9QUOrYmVCoOmbzADrGhNM7zZDz2tjyGLJKKj0LxJqoBlOdQNriwrL1k+vIFF3cca7dEpiG1VoMVbp+K4b8C/UPZL76/dc0h1pV9WEm5N2czivmv6baB6MMIZc39CdvrjOnWm1Py5cEANIwzwXy064iI5arnw49LHhCEFxAoupXND1Oa8AOcR+j98Ghx5yXdVhwsdBTfs34MwhudIJz3RuwWbyPCq8wAT0d1eLNKB8mM9VVyZQnINvMycqWIGspllGFq9kYQ7LN4HqMsJ0ZBvKWNXFwLHLdcvF8QudfxTpUlVLFjMvAtcoQ3imqpK7PTZhItayrDC5F6hr2006+CloZdR+Jd2lbSFSY2Pmow1o5mXYyb32MSm0YR7tZ0HRMoJX9/pN2rLn/JiyJcRWEy4iS9tNXNm9EkxBa1l4TmxwG632Sf3CAdQkEEexTuyTaImG6l9rHz0DXVoh8UzqvNNrFGwKG2fcAzI4o8O+u0/Ck+2+briEHYT5SvwpQRmjGcAUYsfWeweBoX5Cd/DstRpzGpNc5hQqGI5UFAlwr3+zBMdqvk0byBP8AoH+5LFvS1q/tFonaFcAe61RvaP6+Z18RkukBjXlln62UEFJhAOo7xP02euZsE1GBYfhxwhH2ZfX+C1CkNkisVL7M4KmD9JJGyTdm+poE9XblaUi3gN9BLt7d5jUkdi0UsizQgkxaFF2nBeOpP1Yqujbxequ8SxS+TiD7o38DLsMS54K23j1bHCXCflyDBbn01lXOWFffNIf2QwnympQKEmASqEXgZe1QEC148h/bwsKYmSjt5aAQ0Ow6K6q4bFbWC7qfnHymylDJWtupLSbSvx6bG3B64KEjnmJjVIP94aGWoYtueqLpguH+M2mnW6fZqm7iz31ICcYeUVvfIhNIAWB3x4+6nWKpFOtTaeY+pwy+ZjWoRSDMlRGSt5SIpt6aRZYZwf9VNW8lfqjdTxK4SkvnqGd8ovvyyFfs8F/fDEZwIdoup24ZxU2ieJz48k134htKiA8zCnpWM8m/DBeSfJeEqjkWFKS8OH5C2emHTKkChQ1qenP7ANShVgVCLdn612soyuCgXHzmBtuNiyhF8PmcHUwPzR6EUQQUqfSpcHlr3JWeNt3V8mHJASSefHaT5DgqpfhgJGkpOXQK8aI2RD9rCtawRc62Ir4N/nL0ZwAOGEJ43TLHS2EXCMe9jwU3mGvrALM7GfcSqkPuzm8LPZaVpsMDvzYdG6C2+o9PkpA9av9IQjs4hNB5I9/LeGvb2xvqQh79Mdg+OQrwFWPsy5UqwQ1HwGSkXC6CanJNMkIVWs/MD44+Tik+3j6Zf8pz1P4k4FpAnNL9NB/hqIBx0ioUR21Kdq1usuWJQfiSzAOAhcwllFes5zYp52/gun1zX7gynRAREMpws2eyiVzhnbT2zef9s4Ng3V,iv:InfsNvwH2YGwX49kNL2wTjx4HfUjRCYEdhs2+e7RZfI=,tag:2iPNnL9EkgP+Jj3+UNskuQ==,type:str]
                ACTION_RUNNER_CONTROLLER_GITHUB_WEBHOOK_SECRET_TOKEN: ENC[AES256_GCM,data:P7DQAMWB6wOWCDh4dMfac43R0DyLFx7FzCKv/DaV+4oWVPjoY0Vmf9BKZ3VEtrQ41kHzZyVDfxr8c3w=,iv:Aa/dVEFBwlnhZcM2g0+kzS6Pgi42ueBqOse1zXAR9n8=,tag:4cz7h7ASY741ibMZNNXBfg==,type:str]
    data:
        - secretKey: ENC[AES256_GCM,data:aBEhe/yJ0STxLZD47gtlMv37nEk0SXsG++epSdwGGpoWXihQdn4=,iv:ZwSs0QO2a77nY8RZQ/gfZFaIZBawAyiF/IA0DKBs5BU=,tag:f6vybNqNYd9OVdcLE7v3bw==,type:str]
          sourceRef:
            storeRef:
                name: ENC[AES256_GCM,data:CJ+bHmwlDGAWoi57d/5WqA==,iv:5PE46f3iHHJtuQI/zH4rcfgmSm+fYaFQ2OHHr6/qP1Y=,tag:fuw86CFzhT3WTH55YGt3tQ==,type:str]
                kind: ENC[AES256_GCM,data:0GsZX8HMlo23+A0dbdQE/r37,iv:Puds1d5aow8ycauvLUv+g4qh11IkYvaPTgMUgjEo1p8=,tag:q35P9C2H5sEadZPLwiQgeQ==,type:str]
          remoteRef:
            key: ENC[AES256_GCM,data:FWhhUkCPSSSAGeqMdxXwGMSXATWqcLNLhRqv8jJiAWkrTQBo,iv:Div/agwQ2xq74+Z09MgHH17tdwna2guP/yW0ORqtPKs=,tag:fxZfU3U6Z8MR+fYvIY/xTA==,type:str]
            property: ENC[AES256_GCM,data:xlyV25jrvkqOQYSKBw9zMZv8JHiJOxtP1o59IBo8mN97fS7VSXw=,iv:NJEvYUZDLRGEa8Z86n1Hpaz1SSlH8qY8p6oCYWyB5Dc=,tag:KXe51OOCWxnlF4EHF0ocJw==,type:str]
        - secretKey: ENC[AES256_GCM,data:JRxqHXl/xz0ScmYajWuQC2TiSJCss0op3UkH6eVuj3B40JFlvLpA4XX9X/qxR7c=,iv:Mb2RZ6Ml8zTdSzpPrP0CbxW2jc6fgfwS/oqy+kSeTN0=,tag:bncyIsUayQ/2KVFSoWOa0g==,type:str]
          sourceRef:
            storeRef:
                name: ENC[AES256_GCM,data:sWf+Ax4gac2pWGYFbw5DDA==,iv:GV9yTCUW+zWrV1njBSoyvongh0AslzwDhYgyTwLHKik=,tag:GSw4MfrMn1/6wO3g0zDQ0A==,type:str]
                kind: ENC[AES256_GCM,data:+GMF7TZnjIQJyQ1p6q9LnvX3,iv:dwmMAdWo/Sv/JhgWfE350bgTvgrwS/Y4E1kf6EwK3Gk=,tag:fSkHBX2lXRRnkhEd4K9KjA==,type:str]
          remoteRef:
            key: ENC[AES256_GCM,data:iO1A/oXTS36TSklduHfo0TzjMlxgKrEidFHgiKpN/hbWeSP6,iv:h4iVfYQw2OCTDj+EYPw8M4BJsWSesBrjTCBZmX/7/6I=,tag:jQou6u5Xj3TnAVeselqTaA==,type:str]
            property: ENC[AES256_GCM,data:arqKI51xJmHjdJVQVkzIKsn9yeA+ZAE0ZFuJDnG3SzKOG7j/C5LnqDilf2tPWWM=,iv:5K0Xx4SV4WOP2drB6WcgLivtGwuP+g6a0Mpdlayl/3U=,tag:K5nkT2WOiYsq+TrE89PJNg==,type:str]
        - secretKey: ENC[AES256_GCM,data:7z8CW1uba8pJW7RUW/5+fT4XY4PLZ0+i8av+aP86jvXYZ1K/RicDMqS/zA==,iv:m6Y5husG+1fxvPDAysP0X6Bd7cDg3JItNq5GRZzRXLE=,tag:wtJKLfbrGwGOkub19oyGRw==,type:str]
          sourceRef:
            storeRef:
                name: ENC[AES256_GCM,data:zTWR8tlmVNi8yW4/HP2jdA==,iv:knwrn7neJeV52zYap1f4zg3QiUzUObd0YctV1gXV82o=,tag:+/cNVg/dJmWlNGBWp4hXLQ==,type:str]
                kind: ENC[AES256_GCM,data:xJ56outJC8YElirNqKtBSa3I,iv:FWpx+T8xiVYM6SbGIbL5k0FWlaer47xruW44Vjg+g7U=,tag:6YDUW8yYlQNdT6f/OFF4cQ==,type:str]
          remoteRef:
            key: ENC[AES256_GCM,data:KWIaYtLGuIBmz3+tB6k1ImkpDBGqHkeyIY5YaYR1kwPe0L16,iv:IVYgmXcy3rV3rNX7N+lR9ECPxnlX5EtgcPAYdeLCNrM=,tag:0+VODGxESBW3JgnMkCBS2g==,type:str]
            property: ENC[AES256_GCM,data:Vl74Oiza+zwS5rRzsg13UKW2O1OHMo+nC+zBJJwJMVeVp6Npra6OerAPOQ==,iv:6+mOD4Uc0O/teCVQb3YKwsDrOB7GTJ4fFPHx9jTFtlw=,tag:vk7Y5NrHeEPUPInoQMlFAA==,type:str]
        - secretKey: ENC[AES256_GCM,data:KmhBms0Ro+n+VGyXxMUCdgJHbudLDrtCO+L2db5GGIwBYZfaWIRjYgxoK8EUn94Ijs2qMA==,iv:5rkGj6a1yqmcWvV7YdAowaVgPyI+iEADFpkEklzHTGo=,tag:qblyitqdM0XX1PfysV9Vtw==,type:str]
          sourceRef:
            storeRef:
                name: ENC[AES256_GCM,data:q3i4TlB3Ulc3Q1tTOBnCVg==,iv:qh+Cn570kxMfs9+G/US7CneA1aRbss3MTFchCSY2sCU=,tag:cW0RpqbfdbVKQRr5YIlz5w==,type:str]
                kind: ENC[AES256_GCM,data:pSSR9tciU+9HDFA8YAv/Jtv5,iv:aYafCBUQvz6y5LscPa49QU1x9wL6cnEq5F6+9m9a16c=,tag:eUrkLcy7SInF8toKoq1PNg==,type:str]
          remoteRef:
            key: ENC[AES256_GCM,data:xSXNsKydx2FrexSSwWwtDhhP2YC4iBbgC0OvFcjn+yeJ/sEP,iv:ldq3DRrTHP2x5OxUc+pTdtc2xgx1eJrsyKHbhJGCnCk=,tag:nLtRc7SnTlaI5Huz2NaMBg==,type:str]
            property: ENC[AES256_GCM,data:QURt+n3OC2hsOnIjDPfjz5Y9R/Pifo5YW/lhDBZ93/FAprzRZkgQDl11S2KTG5nwvFtNog==,iv:R+urC8F+64imhwldEWXRN8x6yy/CpDxcWACYuFcFVuY=,tag:Ikz1XJBmISEM1SZJYcqu5Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17hs3k9rfp2n3xn38nl8kks4sppj4n98dxfxdhe2x73d86sh0t54slpn33d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNeCtiQ3JvWTY2aitLZk9a
            V3Rkb2R2Zld0aVRlcXhXVmpvUDdyeDJsYXowCkVWT2VKT2drV2xMaEs1Q3lUYlQ1
            bURxRXU3WEk3THNNdjBUc2QvbENSRDAKLS0tIFpYdkhzSXVRK3Zna2cvRTBWNVIw
            bktVQytlbXd5bjlRcm1RcFlDZlFyNWcKOAnNdNv2BTxHlj3zvX2EF2zO/45C7cZW
            MxULnKs8Gz9N3fp52axYMpL1lnZZXDj+2WRG/ePs+P4bB7zONZghnA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-11T11:41:02Z"
    mac: ENC[AES256_GCM,data:aCQ4frHleGU0NZWQbaYH0BgQkMfKcR6Ah6GKqtbDcqeTQksWrLi+Ivte3z4C7PIKCfuucqV7/0G9Ac3Of8Vodi4TS2glV0b0dLYyFWxqmebD+xnFi+hipPeTVoJCdKub+O4p6r/9LYz4oFf7fJ7dIhpjYZg/o5V7otcJBSMAP6g=,iv:Zh74Kiy0u2RRpFKzVYsGxuV7vyfZmJukSPtYE/9lMRg=,tag:Oqog96m/+ddMX94gntHu+w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
