---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: actions-runner-controller-auth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: actions-runner-controller-auth-secret
    template:
      engineVersion: v2
      data:
        ACTION_RUNNER_CONTROLLER_GITHUB_APP_ID: |-
          {{ .ACTION_RUNNER_CONTROLLER_GITHUB_APP_ID }}
        ACTION_RUNNER_CONTROLLER_GITHUB_INSTALLATION_ID: |-
          {{ .ACTION_RUNNER_CONTROLLER_GITHUB_INSTALLATION_ID }}
        ACTION_RUNNER_CONTROLLER_GITHUB_PRIVATE_KEY: |-
          {{ .ACTION_RUNNER_CONTROLLER_GITHUB_PRIVATE_KEY }}
        ACTION_RUNNER_CONTROLLER_GITHUB_WEBHOOK_SECRET_TOKEN: |-
          {{ .ACTION_RUNNER_CONTROLLER_GITHUB_WEBHOOK_SECRET_TOKEN }}
  data:
  - secretKey: ACTION_RUNNER_CONTROLLER_GITHUB_APP_ID
    sourceRef:
      storeRef:
        name: bitwarden-fields
        kind: ClusterSecretStore
    remoteRef:
      key: c05babde-d74b-4fda-ad46-cfd28d8b98cd
      property: ACTION_RUNNER_CONTROLLER_GITHUB_APP_ID
  - secretKey: ACTION_RUNNER_CONTROLLER_GITHUB_INSTALLATION_ID
    sourceRef:
      storeRef:
        name: bitwarden-fields
        kind: ClusterSecretStore
    remoteRef:
      key: c05babde-d74b-4fda-ad46-cfd28d8b98cd
      property: ACTION_RUNNER_CONTROLLER_GITHUB_INSTALLATION_ID
  - secretKey: ACTION_RUNNER_CONTROLLER_GITHUB_PRIVATE_KEY
    sourceRef:
      storeRef:
        name: bitwarden-fields
        kind: ClusterSecretStore
    remoteRef:
      key: c05babde-d74b-4fda-ad46-cfd28d8b98cd
      property: ACTION_RUNNER_CONTROLLER_GITHUB_PRIVATE_KEY
  - secretKey: ACTION_RUNNER_CONTROLLER_GITHUB_WEBHOOK_SECRET_TOKEN
    sourceRef:
      storeRef:
        name: bitwarden-fields
        kind: ClusterSecretStore
    remoteRef:
      key: c05babde-d74b-4fda-ad46-cfd28d8b98cd
      property: ACTION_RUNNER_CONTROLLER_GITHUB_WEBHOOK_SECRET_TOKEN

