---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gha-runner-scale-set2
spec:
  interval: 30m
  chart:
    spec:
      chart: gha-runner-scale-set
      version: 0.11.0
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: flux-system
  driftDetection:
    mode: enabled
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: gha-runner-scale-set-controller
      namespace: actions-runner-system
  valuesFrom:
    - targetPath: githubConfigSecret.github_app_id
      kind: Secret
      name: actions-runner-controller-auth-secret
      valuesKey: ACTION_RUNNER_CONTROLLER_GITHUB_APP_ID
    - targetPath: githubConfigSecret.github_app_installation_id
      kind: Secret
      name: actions-runner-controller-auth-secret
      valuesKey: ACTION_RUNNER_CONTROLLER_GITHUB_INSTALLATION_ID
    - targetPath: githubConfigSecret.github_app_private_key
      kind: Secret
      name: actions-runner-controller-auth-secret
      valuesKey: ACTION_RUNNER_CONTROLLER_GITHUB_PRIVATE_KEY
  values:
    nameOverride: gha-runner-scale-set2
    runnerScaleSetName: gha-runner-scale-set2
    githubConfigUrl: https://github.com/Tomyail/ai-trigger
    minRunners: 0
    maxRunners: 5
    containerMode:
      type: kubernetes
      kubernetesModeWorkVolumeClaim:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 10Gi
    template:
      spec:
        containers:
          - name: runner
            image: ghcr.io/onedr0p/actions-runner:2.322.0@sha256:9db27092b7caab08b1dc08d5e639a3340f6e0d6ae2f91aaf93e740bd28ad9306
            command: ["/home/runner/run.sh"]
            env:
              - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
                value: "false"
    controllerServiceAccount:
      name: gha-runner-scale-set-controller
      namespace: actions-runner-system
