---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflared-tunnel
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: cloudflared-tunnel-secret
    template:
      engineVersion: v2
      data:
        credentials.json: |
          {
            "AccountTag": "{{ .account_tag }}",
            "TunnelSecret": "{{ .tunnel_secret }}",
            "TunnelID": "${SECRET_CLOUDFLARE_TUNNEL_ID}"
          }
  data:
    - secretKey: account_tag
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: d3906233-c03d-486b-b13a-790102a50ea6
        property: account_tag
    - secretKey: tunnel_secret
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: d3906233-c03d-486b-b13a-790102a50ea6
        property: tunnel_secret
    - secretKey: tunnel_id
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        key: d3906233-c03d-486b-b13a-790102a50ea6
        property: tunnel_id
