---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-ssd
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.50.200
  share: /export/ssd_data
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions: ["hard", "noatime", "nconnect=12"]

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-hdd
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.50.200
  share: /export/hdd_data
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions: ["hard", "noatime", "nconnect=12"]

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-omv-ssd
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.50.200
  share: /export/ssd_data
  subDir: $${pvc.metadata.namespace}/$${pvc.metadata.name}/$${pv.metadata.name}
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions: ["hard", "noatime"]

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-omv-hdd
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.50.200
  share: /export/hdd_data
  subDir: $${pvc.metadata.namespace}/$${pvc.metadata.name}/$${pv.metadata.name}
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions: ["hard", "noatime"]


---

apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: nfs-snapshot
driver: nfs.csi.k8s.io
deletionPolicy: Delete
