---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-ssd
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.50.200
  share: /export/ssd_data
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions: ["hard", "noatime", "nconnect=12"]

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-hdd
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.50.200
  share: /export/hdd_data
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions: ["hard", "noatime", "nconnect=12"]

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-omv-ssd
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.50.200
  share: /export/ssd_data
  subDir: $${pvc.metadata.namespace}/$${pvc.metadata.name}/$${pv.metadata.name}
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions: ["hard", "noatime"]


---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-omv-hdd
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.50.200
  share: /export/hdd_data
  subDir: $${pvc.metadata.namespace}/$${pvc.metadata.name}/$${pv.metadata.name}
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions: ["hard", "noatime"]



---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-omv-hdd-media
provisioner: nfs.csi.k8s.io
reclaimPolicy: Retain
volumeBindingMode: Immediate

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: omv-media-pv
  annotations:
    pv.kubernetes.io/provisioned-by: nfs.csi.k8s.io
spec:
  capacity:
    storage: 10Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-omv-hdd-media
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: 192.168.50.200#/export/media#media
    volumeAttributes:
      server: 192.168.50.200
      share: /export/media

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: omv-media-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Ti
  storageClassName: nfs-omv-hdd-media
  volumeName: omv-media-pv


---


apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: nfs-snapshot
driver: nfs.csi.k8s.io
deletionPolicy: Delete