---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app external-dns-adguard-home
spec:
  interval: 30m
  chart:
    spec:
      chart: external-dns
      version: 1.16.1
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      strategy: rollback
      retries: 3
  values:
    # domainFilters: ["internal.${SECRET_DOMAIN}"]
    provider:
      name: webhook
      webhook:
        image:
          repository: ghcr.io/muhlba91/external-dns-provider-adguard
          tag: v8.0.1@sha256:267761a55dde38b7cba7b3bff59d0437402538a29659b03144dc9c132c887444
          pullPolicy: IfNotPresent
        env:
          - name: ADGUARD_URL
            value: http://192.168.50.137:80
          - name: &name ADGUARD_USER
            valueFrom:
              secretKeyRef:
                name: &secret external-dns-adguard-home-secret
                key: *name
          - name: &name ADGUARD_PASSWORD
            valueFrom:
              secretKeyRef:
                name: *secret
                key: *name
          - name: SERVER_HOST
            value: 0.0.0.0
        securityContext:
          readOnlyRootFilesystem: true
    interval: 1h
    triggerLoopOnEvent: true
    policy: sync
    registry: noop

    extraArgs:
      - --webhook-provider-url=http://localhost:8888
      - --ingress-class=internal
    podAnnotations:
      secret.reloader.stakater.com/reload: *secret
    logLevel: debug
