---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/notification.toolkit.fluxcd.io/provider_v1beta3.json
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: gitlab
spec:
  type: gitlab
  address: https://gitlab.${SECRET_DOMAIN}/tomyail/cloud-config
  secretRef:
    name: gitlab-token-secret
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/notification.toolkit.fluxcd.io/alert_v1beta3.json
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: gitlab
spec:
  providerRef:
    name: gitlab
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: "*"
