---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prefect-server
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: prefect-server-secret
    template:
      engineVersion: v2
      data:
        INIT_POSTGRES_DBNAME: prefect-dev-db
        INIT_POSTGRES_HOST: dev-postgres16-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: '{{ .username }}'
        INIT_POSTGRES_PASS: '{{ .password }}'
        INIT_POSTGRES_SUPER_PASS: '{{ .super_password }}'
        connection-string: "postgresql+asyncpg://{{.username}}:{{.password}}@dev-postgres16-rw.database.svc.cluster.local/prefect-dev-db"
  data:
    - secretKey: super_password
      remoteRef:
        key: cloudnative-pg
        property: password
    - secretKey: username
      remoteRef:
        key: prefect-server-dev-db
        property: username
    - secretKey: password
      remoteRef:
        key: prefect-server-dev-db
        property: password
