---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app prefect-server
spec:
  chart:
    spec:
      chart: prefect-server
      version: 2025.2.8021311
      sourceRef:
        kind: HelmRepository
        name: prefect
        namespace: flux-system
  interval: 15m
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  driftDetection:
    mode: enabled
    ignore:
      - paths:
          - /spec/containers/resources/limits
        target:
          kind: Pod
  values:
    server:
      image:
        repository: prefecthq/prefect
        prefectTag: 3-python3.9-kubernetes
        debug: true

      prefectApiUrl: http://localhost:4200/api

      uiConfig:
        enabled: true
        prefectUiApiUrl: "https://prefect.${SECRET_DOMAIN}/api"

      env:
        - name: PREFECT_API_DATABASE_MIGRATE_ON_START
          value: "True"

      # # Autoscaling configuration
      # # requests MUST be specified if using an HPA, otherwise the HPA will not know when to trigger a scale event
      # autoscaling:
      #   enabled: false
      #   minReplicas: 1
      #   maxReplicas: 100
      #   targetCPU: 80
      #   targetMemory: 80

      # # requests MUST be specified if using an HPA, otherwise the HPA will not know when to trigger a scale event
      # resources:
      #   requests:
      #     # cpu: 25m
      #     # memory: 105M
      #   limits:
      #     # memory: 105M

      ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
      podSecurityContext:
        runAsUser: 1000
        runAsNonRoot: true
        fsGroup: 1002
      ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container
      containerSecurityContext:
        runAsUser: 1000
        runAsNonRoot: true
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false

    extraInitContainers:
      - name: init-db
        image: ghcr.io/onedr0p/postgres-init:16
        envFrom:
          - secretRef:
              name: prefect-server-secret

    ## Service configuration
    service:
      type: ClusterIP
      port: 4200

    # Ingress configuration
    ingress:
      enabled: true
      className: internal
      host:
        hostname: &host prefect.${SECRET_DOMAIN}
        path: /
        pathType: Prefix
      annotations:
        external-dns.alpha.kubernetes.io/target: "192.168.50.160,192.168.50.182,192.168.50.234"
        nginx.ingress.kubernetes.io/whitelist-source-range: |
          10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
      tls: true

    # https://discourse.prefect.io/t/how-to-use-external-postgres-when-deploy-by-helm-chart/2501/4
    postgresql:
      enabled: false
    secret:
      create: false
      name: prefect-server-secret
      # ... filled with valuesFrom below
      port: 5432
