---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gatus
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: gatus-secret
    template:
      engineVersion: v2
      data:
        PUSHOVER_TOKEN: "{{ .gatus_pushover_token }}"
        PUSHOVER_USER_KEY: "{{ .gatus_user_key }}"
        INIT_POSTGRES_DBNAME: gatus
        INIT_POSTGRES_HOST: dev-postgres16-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .username }}"
        INIT_POSTGRES_PASS: "{{ .password }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .super_password }}"
  data:
    - secretKey: super_password
      remoteRef:
        key: cloudnative-pg
        property: password
    - secretKey: username
      remoteRef:
        key: gatus
        property: username
    - secretKey: password
      remoteRef:
        key: gatus
        property: password
    - secretKey: gatus_user_key
      remoteRef:
        key: pushover_gatus_dev
        property: username
    - secretKey: gatus_pushover_token
      remoteRef:
        key: pushover_gatus_dev
        property: password
