---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./echo-server/ks.yaml
  - ./home-assistant/ks.yaml
  - ./jellyseerr/ks.yaml
  - ./cookiecloud/ks.yaml
  - ./uptime-kuma/ks.yaml
  - ./minio/ks.yaml
  - ./navidrome/ks.yaml
  - ./hajimari/ks.yaml
  - ./prefect/ks.yaml
  - ./sync-mino/ks.yaml