---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/notification.toolkit.fluxcd.io/receiver_v1.json
apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: gitlab-dev
spec:
  type: gitlab
  events:
    - "Push Hook"
    - "Tag Push Hook"
  secretRef:
    name: gitlab-webhook-token-secret
  resources:
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: GitRepository
      name: home-kubernetes
      namespace: flux-system
    # - apiVersion: kustomize.toolkit.fluxcd.io/v1
    #   kind: Kustomization
    #   name: cluster
    #   namespace: flux-system
    # - apiVersion: kustomize.toolkit.fluxcd.io/v1
    #   kind: Kustomization
    #   name: cluster-apps
    #   namespace: flux-system
