# ---
# originRequest:
#   originServerName: external-old.${SECRET_DOMAIN}

ingress:
  - hostname: "*.${SECRET_DOMAIN}"
    service: http://nginx-external-controller.network.svc.cluster.local:80
  - service: http_status:404
