---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "flux-webhook-gatus-ep"
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: "flux-webhook"
        group: external
        url: "https://flux-webhook-github.${SECRET_DOMAIN}"
        interval: 1m
        ui:
          hide-hostname: true
        conditions:
          - "[STATUS] == 404"
        alerts:
          - type: pushover
