apiVersion: v1
kind: Endpoints
metadata:
  name: gitlab
subsets:
  - addresses:
      - ip: 192.168.50.178
    ports:
      - port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab
spec:
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitlab
  annotations:
    external-dns.alpha.kubernetes.io/target: external-old.${SECRET_DOMAIN}
spec:
  ingressClassName: external
  rules:
    - host: gitlab.${SECRET_DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gitlab
                port:
                  number: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "gitlab-gatus-ep"
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: "gitlab"
        group: external
        url: "https://gitlab.${SECRET_DOMAIN}"
        interval: 1m
        ui:
          hide-hostname: true
          hide-url: true
        conditions:
          - "[STATUS] == 200"
        alerts:
          - type: pushover

