apiVersion: v1
kind: Endpoints
metadata:
  name: iyuu
subsets:
  - addresses:
      - ip: 192.168.50.170
    ports:
      - port: 8780
---
apiVersion: v1
kind: Service
metadata:
  name: iyuu
spec:
  ports:
    - port: 80
      targetPort: 8780
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: iyuu-internal
  annotations:
    external-dns.alpha.kubernetes.io/target: "192.168.50.160,192.168.50.182,192.168.50.234"
spec:
  ingressClassName: internal
  rules:
    - host: iyuu.${SECRET_DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: iyuu
                port:
                  number: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "iyuu-gatus-ep"
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: "iyuu"
        group: internal
        url: 1.1.1.1
        interval: 1m
        ui:
          hide-hostname: true
          hide-url: true
        dns:
          query-name: "iyuu.${SECRET_DOMAIN}"
          query-type: A
        conditions:
          - "len([BODY]) == 0"
        alerts:
          - type: pushover
      - name: "iyuu"
        group: internal-up
        url: "https://iyuu.${SECRET_DOMAIN}"
        interval: 1m
        ui:
          hide-hostname: true
          hide-url: true
        conditions:
          - "[STATUS] == 200"
        alerts:
          - type: pushover

