apiVersion: v1
kind: Endpoints
metadata:
  name: pve
subsets:
  - addresses:
      - ip: 192.168.50.100
    ports:
      - port: 8006
---
apiVersion: v1
kind: Service
metadata:
  name: pve
spec:
  ports:
    - port: 443
      targetPort: 8006
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pve-internal
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    external-dns.alpha.kubernetes.io/target: "192.168.50.160,192.168.50.182,192.168.50.234"
spec:
  ingressClassName: internal
  rules:
    - host: pve.${SECRET_DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pve
                port:
                  number: 443
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "pve-gatus-ep"
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: "pve"
        group: internal
        url: 1.1.1.1
        interval: 1m
        ui:
          hide-hostname: true
          hide-url: true
        dns:
          query-name: "pve.${SECRET_DOMAIN}"
          query-type: A
        conditions:
          - "len([BODY]) == 0"
        alerts:
          - type: pushover
      - name: "pve"
        group: internal-up
        url: "https://pve.${SECRET_DOMAIN}"
        interval: 1m
        ui:
          hide-hostname: true
          hide-url: true
        conditions:
          - "[STATUS] == 200"
        alerts:
          - type: pushover

