---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-login
  target:
    name: tailscale-secret
    template:
      engineVersion: v2
      data:
        clientID: "{{ .username }}"
        clientSecret: "{{.password }}"
  data:
    - secretKey: password
      remoteRef:
        key: tailscale_k8s_oauth
        property: password
    - secretKey: username
      remoteRef:
        key: tailscale_k8s_oauth
        property: username
