---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app tailscale
spec:
  interval: 30m
  chart:
    spec:
      chart: tailscale-operator
      version: 1.82.5
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    fullnameOverride: tailscale
    apiServerProxyConfig:
      mode: "noauth"
    oauth:
    # todo FIXME 
      clientId: kkkAXZK3gS11CNTRL
      clientSecret: tskey-client-kkkAXZK3gS11CNTRL-hn7UxCkWM92ukkzeBAW8A2h1idgARaC77
    podAnnotations:
      secret.reloader.stakater.com/reload: tailscale-secret
