---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: uptime-kuma
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
    - name: volsync
      namespace: volsync-system
  values:
    controllers:
      uptime-kuma:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: louislam/uptime-kuma
              tag: 1.23.16
            resources:
              requests:
                memory: 400M
                cpu: 15m
              limits:
                memory: 600M
                cpu: 200m

    service:
      app:
        controller: uptime-kuma
        ports:
          http:
            port: 3001
    ingress:
      app:
        annotations:
          external-dns.alpha.kubernetes.io/target: "192.168.50.160,192.168.50.182,192.168.50.234"
        className: internal
        hosts:
          - host: uptime-dev.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      config:
        existingClaim: uptime-kuma
        globalMounts:
          - path: /app/data
