---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: calibre-web-automated
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      calibre-web-automated:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: crocodilestick/calibre-web-automated
              tag: V3.0.4
            env:
              CACHE_DIR: /cache
              TZ: "Asia/Shanghai"
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 768Mi
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  initialDelaySeconds: 60
                  failureThreshold: 45
                  periodSeconds: 5
    service:
      app:
        controller: calibre-web-automated
        ports:
          http:
            port: 8083
    ingress:
      internal:
        className: internal
        annotations:
          external-dns.alpha.kubernetes.io/target: "192.168.50.160,192.168.50.182,192.168.50.234"
        hosts:
          - host: &host "books.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
      app:
        annotations:
          external-dns.alpha.kubernetes.io/target: external-old.${SECRET_DOMAIN}
        className: external
        hosts:
          - host: books.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      config:
        enabled: true
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: nfs-ssd
        globalMounts:
          - path: /config
      cache:
        type: emptyDir
      media:
        enabled: true
        accessMode: ReadWriteOnce
        size: 10Gi
        storageClass: nfs-ssd
        globalMounts:
          - path: /cwa-book-ingest
            subPath: cwa-book-ingest
          - path: /calibre-library
            subPath: calibre-library
